## Vectorization comparizon

In [2]:
import numpy as np
import time

a = np.random.rand(10000000)
b = np.random.rand(10000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print("Vectorized version")
print("Time: " + str(1000*(toc - tic)) + "ms")
print("Value: " + str(c))

print()

tic = time.time()
c = 0
for i in range(10000000):
    c += a[i]*b[i]
toc = time.time()

print("Looped version")
print("Time: " + str(1000*(toc - tic)) + "ms")
print("Value: " + str(c))


Vectorized version
Time: 78.12380790710449ms
Value: 2500411.73909

Looped version
Time: 15198.485612869263ms
Value: 2500411.73909


In [3]:
v = np.random.rand(1000)
expV = np.exp(v)
logV = np.log(v)

## Broadcasting

In [5]:
import numpy as np
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [22]:
cal = A.sum(axis=0)   # Axis denotes if rows or columns should be summed, 0 =col
print(cal)

[  59.   239.   155.4   76.9]


In [21]:
percentage = 100*A/cal.reshape(1,4)   # Reshape transforms cal from a vector with 4 elements to a 1x4 matrix (not necessary)
print(percentage)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [41]:
two_by_tree = np.array([[10, 20, 30], 
                        [10, 20, 30]])

one_by_tree = np.array([1, 2, 3])

# numpy copies one_by_tree and transforms it to a 2x3 matrix by adding itself as another row
broadcast_add = two_by_tree + one_by_tree
print(broadcast_add)

[[11 22 33]
 [11 22 33]]


## Python tips and tricks

In [58]:
import numpy as np

# Creates a 1-rank array instead of a 5x1 matrix
a = np.random.randn(5)

print(a)
print(np.shape(a))

[-0.83673392 -0.42574777  0.97605512  0.14371875 -0.35644109]
(5,)


In [68]:
# Tranposing this does not work
print(a.T)
print(np.shape(a.T))

[-0.33136687  0.69494029  2.36567862 -0.86241802  1.84742206]
(5,)


In [60]:
# However if we specify matrix format we get the desirded shape
a = np.random.randn(5,1)
print(a)
print(np.shape(a))

[[ 0.62434627]
 [ 0.11400525]
 [-0.050146  ]
 [-1.18686902]
 [ 1.31237951]]
(5, 1)


In [61]:
# Then transpose works again
print(a.T)
print(np.shape(a.T))

[[ 0.62434627  0.11400525 -0.050146   -1.18686902  1.31237951]]
(1, 5)


In [63]:
# Alteratively we can reshape if we recieve data in 1-rank array format
a = np.random.randn(5)
b = a.reshape(5,1)
print(b)
print(np.shape(b))

[[-0.33136687]
 [ 0.69494029]
 [ 2.36567862]
 [-0.86241802]
 [ 1.84742206]]
(5, 1)
